### ISSUE TITLE
请问沉浸式状态栏是如何做的呢

### ISSUE THREAD

**Issue by yangxiaoge** [huanxsd/flutter_shuqi#1]
如题，我在theme中了设置了，但是无效。

![image](https://user-images.githubusercontent.com/12471093/51593074-2cabf600-1f2c-11e9-8249-9c6159511b30.png)

**Comment by jiang111** [comment]
这段

`if (Platform.isAndroid) {
    SystemUiOverlayStyle systemUiOverlayStyle = SystemUiOverlayStyle(statusBarColor: Colors.transparent);
    SystemChrome.setSystemUIOverlayStyle(systemUiOverlayStyle);
  }`

**Comment by huanxsd** [comment]
楼上正解

**Comment by spemagic** [comment]
如果有AppBar，状态栏会根据Brightness自动调整，直接调用SystemChrome.setSystemUIOverlayStyle无效

**Comment by paozhuanyinyu** [comment]
设置了
if (Platform.isAndroid) { SystemUiOverlayStyle systemUiOverlayStyle = SystemUiOverlayStyle(statusBarColor: Colors.transparent); SystemChrome.setSystemUIOverlayStyle(systemUiOverlayStyle); }
状态栏设置成白色，但是状态栏上的字也是白色看不见字；
