### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by dewi23** [huanxsd/flutter_shuqi#10]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
lib/home/home_banner.dart:36:9: Error: No named parameter with the name 'interval'.
        interval: const Duration(seconds: 5),
        ^^^^^^^^
file:///C:/Users/win/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/carousel_slider-1.3.0/lib/carousel_slider.dart:9:3: Context: Found this candidate, but the arguments don't match.
  CarouselSlider({
  ^
Compiler failed on E:\MyFlutterCode\flutter_shuqi-master\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by MaoHui2016** [comment]
我也是这个错误，请问咋解决的

**Comment by huanxsd** [comment]
CarouselSlider版本问题，可以直接删掉这行代码

**Comment by huanxsd** [comment]
flutter使用最新stable版本（1.5.4-hotfix.2），项目使用最新代码试下。
