### ISSUE TITLE
请问刚下载下来执行flutter run就报错：Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'. oldImageStream?.removeListener(_handleImageChanged);

### ISSUE THREAD

**Issue by Watchet** [huanxsd/flutter_shuqi#13]
报错内容如截图（Flutter 环境是没有问题的）：
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'. oldImageStream?.removeListener(_handleImageChanged);

![image](https://user-images.githubusercontent.com/8310796/58448320-13b18c80-813a-11e9-98f4-eab58a651a61.png)

**Comment by wjkk** [comment]
请问这个问题解决了么

**Comment by wjkk** [comment]
用stable版本的flutter试试

**Comment by huanxsd** [comment]
使用最新stable版本，最新项目代码试下
