### ISSUE TITLE
非首章进入时pageIndex出错

### ISSUE THREAD

**Issue by AlexVincent525** [huanxsd/flutter_shuqi#17]
当传入非第一章的时候，部分代码没有进行判断，导致进入时为传入章得上一章的最后一页，且点击时会重置一次index，才能继续切换。
相关代码：
https://github.com/huanxsd/flutter_shuqi/blob/45681ac6c372f70e39080cd62322a173c2d7cecc/lib/reader/reader_scene.dart#L210-L214
在该位置，首次`build`的`page`一定为`0 - preArticle.pageCount`，因为`itemBuilder`的`index`首次`build`时必为0。此处需要更多的判断。

**Comment by AlexVincent525** [comment]
经过简易研究，已发现问题所在，处理方案如下：

 · 该处`pageController`改为空值，并添加`bool`变量`firstLoaded`为`false`。
https://github.com/huanxsd/flutter_shuqi/blob/45681ac6c372f70e39080cd62322a173c2d7cecc/lib/reader/reader_scene.dart#L29
 · 监听移至后文定位处。
https://github.com/huanxsd/flutter_shuqi/blob/45681ac6c372f70e39080cd62322a173c2d7cecc/lib/reader/reader_scene.dart#L43
 · 在此处`if`后`setState`处改写：
```
if (jumpType != PageJumpType.stay) {
  ......
}

if (!firstLoaded) {
  pageController = PageController(
    initialPage: preArticle != null ? preArticle.pageCount : 0,
    keepPage: false,
  )..addListener(onScroll);
  firstLoaded = true;
}

if (mounted) setState(() {});
```
https://github.com/huanxsd/flutter_shuqi/blob/45681ac6c372f70e39080cd62322a173c2d7cecc/lib/reader/reader_scene.dart#L99-L103

上述修改后，如果传入了非首章的章节，能够正确判断`preArticle`的状态，并且保证只有一次初始化`pageController`且为正确`index`，保证翻页和显示页的正常。

**Comment by huanxsd** [comment]
这个项目的阅读页仅做演示，不适合实际项目。

**Comment by AlexVincent525** [comment]
更改这部分逻辑不影响演示。

**Comment by AlexVincent525** [comment]
Closing with no response with action taken.
