### ISSUE TITLE
flutter run 失败了

### ISSUE THREAD

**Issue by f1ery** [huanxsd/flutter_shuqi#28]
Compiler message:
../../.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-1.1.1/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../flutter/packages/flutter/lib/src/painting/image_provider.dart:574:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^

FAILURE: Build failed with an exception.

**Comment by antiphy** [comment]
pubspec.yaml modify this line

cached_network_image: ^1.1.1

to

cached_network_image: ^2.2.0+1

and build.gradle
classpath 'com.android.tools.build:gradle:3.3.1'

**Comment by huanxsd** [comment]
依赖已全部升级到最新
