### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by hlj2722** [huanxsd/flutter_shuqi#9]
版本
D:\Android\flutter_shuqi>flutter --version
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (11 days ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

D:\Android\flutter_shuqi>dart --version
Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "windows_x64"

D:\Android\flutter_shuqi>
--------------------------------------------------------------------------------------

执行 flutter run 时报错

Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  D:\Android\flutter_shuqi\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found
.
  D:\Android\flutter_shuqi\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  D:\Android\flutter_shuqi\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:272: error: resource android:attr/fontVariationSettings not found.
  D:\Android\flutter_shuqi\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:272: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\HLJ\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\9fb46f03dcbfd50bb5d0283e37b1a7f6\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\HLJ\AppData\Local\Android\Sdk\platforms\android-27\android.jar\
          --manifest\
          D:\Android\flutter_shuqi\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\Android\flutter_shuqi\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\Android\flutter_shuqi\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\Android\flutter_shuqi\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.shuqi\
          -0\
          apk\
          --output-text-symbols\
          D:\Android\flutter_shuqi\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\HLJ\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.0.aar\24036263137ade4f618479c217bcfe58\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:att
r/dialogCornerRadius not found.

  D:\Android\flutter_shuqi\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\Users\HLJ\.gradle\caches\transforms-1\files-1.1\core-1.0.0.aar\cfc7fcfeba2756c942fb5d91bd098f8b\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSetti
ngs not found.

  C:\Users\HLJ\.gradle\caches\transforms-1\files-1.1\core-1.0.0.aar\cfc7fcfeba2756c942fb5d91bd098f8b\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found
.

  error: failed linking references.
  Command: C:\Users\HLJ\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\9fb46f03dcbfd50bb5d0283e37b1a7f6\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\HLJ\AppData\Local\Android\Sdk\platforms\android-27\android.jar\
          --manifest\
          D:\Android\flutter_shuqi\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\Android\flutter_shuqi\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\Android\flutter_shuqi\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\Android\flutter_shuqi\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.shuqi\
          -0\
          apk\
          --output-text-symbols\
          D:\Android\flutter_shuqi\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        12.5s
*******************************************************************************************

**Comment by wjkk** [comment]
去android/app/build.gradle里把compileSdkVersion 改成最低28后试试

**Comment by huanxsd** [comment]
flutter使用最新stable版本（1.5.4-hotfix.2），项目使用最新代码试下。
